#!/bin/bash

###############################################################################
## ISCTE-IUL: Trabalho prático de Sistemas Operativos - Parte 1
##
## Este módulo destina-se a realizar operações de I/O utilitárias.
## Não deverá ser alterado nem submetido com o trabalho.
##
## Nome do Módulo: debug.sh
## Descrição/Explicação do Módulo:
##    Mensagens de DEBUG para os scripts
##    SYNTAX: debug [<opcional 1>] [<opcional 2>] ... [<opcional n>]
##    Basicamente, o módulo escreve "@DEBUG ", e depois mostra todos os
##    argumentos que sejam passados, separados por "<>"
##    Dica: Quando afetarem variáveis, façam e.g., "var1=3 && debug var1 $var1"
##          para verem logo o valor das variáveis.
##       No final, para desaparecerem as mensagens de DEBUG, basta comentar a última linha deste script,
##       e não é preciso mexer nos vossos scripts. Deste modo, podem ativar e desativar o Debug quando quiserem.
##    Este script não causa terminação do script que o invoca e retorna 0
##
## @param $1..n: Informações de debug que o aluno queira mostrar. Estas
##               informações são mostradas separadas com <> para que se possa
##               perceber se há caracteres não desejados
###############################################################################

exit 0
. /home/so/reference/define-colours.sh
echo -ne "${DARKGRAY}@DEBUG"; for arg in "$@"; do echo -ne " [$arg]"; done; echo -e "${NO_COLOUR}"; exit 0